/* SPDX-License-Identifier: Apache-2.0 OR GPL-2.0-or-later */
/*
 * Display engine scalers: shared definitions of the video (VSU) and
 * graphic (GSU) scalers and of the coefficient tables.
 */
#ifndef __DE_SCALER_H__
#define __DE_SCALER_H__

#include <dpy/dpy_types.h>

/* scaling steps/phases are fixed point with these fraction widths */
#define DE_VSU_FRAC		19
#define DE_GSU_FRAC		18
#define DE_VSU_PHASES		32
#define DE_GSU_PHASES		16

/* smallest window the scalers handle */
#define DE_SCALER_MIN_W		32
#define DE_SCALER_MIN_H		8

#define DE_SCALER_BUCKETS	16

/* [bucket][phase] tables, generated by tools/gen_scaler_coef.py */
extern const uint32_t de_vsu_coef_y_h0[DE_SCALER_BUCKETS * DE_VSU_PHASES];
extern const uint32_t de_vsu_coef_y_h1[DE_SCALER_BUCKETS * DE_VSU_PHASES];
extern const uint32_t de_vsu_coef_y_v[DE_SCALER_BUCKETS * DE_VSU_PHASES];
extern const uint32_t de_vsu_coef_c_h0[DE_SCALER_BUCKETS * DE_VSU_PHASES];
extern const uint32_t de_vsu_coef_c_h1[DE_SCALER_BUCKETS * DE_VSU_PHASES];
extern const uint32_t de_vsu_coef_c_v[DE_SCALER_BUCKETS * DE_VSU_PHASES];
extern const uint32_t de_gsu_coef[DE_SCALER_BUCKETS * DE_GSU_PHASES];

/*
 * Pick the zoom bucket for a scaling @step with @frac fraction bits:
 * 1 for up scaling and ratio 1, eighths up to 2, quarters up to 3,
 * then 3.x, 4.x and everything above.
 */
static inline unsigned int de_scaler_bucket(uint32_t step, unsigned int frac)
{
	uint32_t eighths = step >> (frac - 3);
	uint32_t ip = eighths >> 3;
	uint32_t fp = eighths & 7;

	if (ip == 0)
		return 1;
	if (ip == 1)
		return 1 + fp;
	if (ip == 2)
		return 9 + (fp >> 1);
	if (ip == 3)
		return 13;
	if (ip == 4)
		return 14;
	return 15;
}

#endif /* __DE_SCALER_H__ */
