CONFIG_COMMON_LIBC_MALLOC_ARENA_SIZE=-1
CONFIG_CRC=y
CONFIG_DEVMEM_SHELL=n
CONFIG_FPU=y
CONFIG_FPU_SHARING=y
CONFIG_HEAP_MEM_POOL_SIZE=65536
CONFIG_LOG=y
CONFIG_LOG_PRINTK=n
CONFIG_MAIN_STACK_SIZE=8192
CONFIG_PRINTK=y
CONFIG_SHELL=n
CONFIG_VDEC=y
