#!/usr/bin/env python3
# Copyright (c) 2026 Yuzuki Tsuru
# SPDX-License-Identifier: Apache-2.0
"""
Make the test pictures of the decoder samples and their reference output.

usage: gen_test_images.py <output dir>   (needs Pillow and numpy)

Writes jpeg/src/test_jpeg.h and png/src/test_png.h (C arrays) and the host
decoded reference pictures (ref_jpeg.rgb, ref_png.rgba) into the output dir.
"""
import math
import os
import sys

from PIL import Image, ImageDraw

import io
import zlib

W, H = 320, 240


def picture(alpha):
    img = Image.new("RGBA" if alpha else "RGB", (W, H))
    d = ImageDraw.Draw(img)
    # vertical gradient background
    for y in range(H):
        c = int(255 * y / (H - 1))
        d.line([(0, y), (W, y)], fill=(c, 255 - c, 128, 255) if alpha else (c, 255 - c, 128))
    # colour bars
    bars = [(255, 255, 255), (255, 255, 0), (0, 255, 255), (0, 255, 0), (255, 0, 255), (255, 0, 0),
            (0, 0, 255), (0, 0, 0)]
    bw = W // len(bars)
    for i, c in enumerate(bars):
        d.rectangle([i * bw, 0, (i + 1) * bw - 1, 60], fill=c + ((255,) if alpha else ()))
    # circle and diagonal
    d.ellipse([110, 80, 210, 180], outline=(255, 255, 255), width=4)
    d.line([(0, H - 1), (W - 1, 70)], fill=(255, 0, 0), width=3)
    d.text((20, 200), "F101 VE DECODE", fill=(255, 255, 255))
    if alpha:
        # fade the right part out
        px = img.load()
        for x in range(W // 2, W):
            a = int(255 * (1 - (x - W // 2) / (W / 2)))
            for y in range(H):
                r, g, b, _ = px[x, y]
                px[x, y] = (r, g, b, a)
    return img


def c_array(name, data):
    lines = ["/* generated by gen_test_images.py */", "#include <stdint.h>", "",
             "static const uint8_t %s[] = {" % name]
    for i in range(0, len(data), 16):
        lines.append("\t" + ", ".join("0x%02x" % b for b in data[i:i + 16]) + ",")
    lines += ["};", ""]
    return "\n".join(lines)


def main():
    out = sys.argv[1]
    os.makedirs(out, exist_ok=True)
    here = os.path.dirname(os.path.abspath(__file__))

    buf = io.BytesIO()
    picture(False).save(buf, "JPEG", quality=90, subsampling=2, optimize=False, progressive=False)
    jpg = buf.getvalue()
    open(os.path.join(here, "jpeg/src/test_jpeg.h"), "w").write(c_array("test_jpeg", jpg))
    Image.open(io.BytesIO(jpg)).convert("RGB").save(os.path.join(out, "ref_jpeg.png"))
    open(os.path.join(out, "ref_jpeg.rgb"), "wb").write(Image.open(io.BytesIO(jpg)).convert("RGB").tobytes())
    open(os.path.join(out, "test.jpg"), "wb").write(jpg)

    buf = io.BytesIO()
    picture(True).save(buf, "PNG")
    png = buf.getvalue()
    os.makedirs(os.path.join(here, "png/src"), exist_ok=True)
    open(os.path.join(here, "png/src/test_png.h"), "w").write(c_array("test_png", png))
    rgba = Image.open(io.BytesIO(png)).convert("RGBA").tobytes()
    open(os.path.join(out, "ref_png.rgba"), "wb").write(rgba)
    # the decoder delivers 32 bit words with R on top: A, B, G, R in memory
    word = b"".join(rgba[i:i + 4][::-1] for i in range(0, len(rgba), 4))
    print("png crc32 of the decoder layout: %08x" % zlib.crc32(word))
    open(os.path.join(out, "test.png"), "wb").write(png)
    print("jpeg %d bytes, png %d bytes" % (len(jpg), len(png)))


main()
