/*
 * Copyright (c) 2026 Yuzuki Tsuru
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_SUN252I_F101_CCU_H_
#define ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_SUN252I_F101_CCU_H_

#include <zephyr/dt-bindings/clock/allwinner-ccu.h>

/*
 * sun252i_f101 (F101) bus clock gate and reset line ids.
 *
 * See allwinner-ccu.h for the id encoding. All F101 bus clocks and reset
 * lines live in the main CCU block.
 */

/* UART bus clocks, gates in UART_BGR_REG (0x090C) */
#define CLK_BUS_UART0			ALLWINNER_CCU_ID(ALLWINNER_CCU_MAIN, 0x090c, 0)
#define CLK_BUS_UART1			ALLWINNER_CCU_ID(ALLWINNER_CCU_MAIN, 0x090c, 1)
#define CLK_BUS_UART2			ALLWINNER_CCU_ID(ALLWINNER_CCU_MAIN, 0x090c, 2)
#define CLK_BUS_UART3			ALLWINNER_CCU_ID(ALLWINNER_CCU_MAIN, 0x090c, 3)
#define CLK_BUS_UART4			ALLWINNER_CCU_ID(ALLWINNER_CCU_MAIN, 0x090c, 4)
#define CLK_BUS_UART5			ALLWINNER_CCU_ID(ALLWINNER_CCU_MAIN, 0x090c, 5)

/* TWI bus clocks, gates in TWI_BGR_REG (0x091C) */
#define CLK_BUS_TWI0			ALLWINNER_CCU_ID(ALLWINNER_CCU_MAIN, 0x091c, 0)
#define CLK_BUS_TWI1			ALLWINNER_CCU_ID(ALLWINNER_CCU_MAIN, 0x091c, 1)
#define CLK_BUS_TWI2			ALLWINNER_CCU_ID(ALLWINNER_CCU_MAIN, 0x091c, 2)

/* SPI bus clocks, gates in SPI_BGR_REG (0x096C) */
#define CLK_BUS_SPI0			ALLWINNER_CCU_ID(ALLWINNER_CCU_MAIN, 0x096c, 0)
#define CLK_BUS_SPI1			ALLWINNER_CCU_ID(ALLWINNER_CCU_MAIN, 0x096c, 1)

/* SPI module clocks, gates in SPI0/1_CLK_REG (0x0940/0x0944) */
#define CLK_SPI0			ALLWINNER_CCU_ID(ALLWINNER_CCU_MAIN, 0x0940, 31)
#define CLK_SPI1			ALLWINNER_CCU_ID(ALLWINNER_CCU_MAIN, 0x0944, 31)

/* DMA clocks, gates in DMA_BGR_REG (0x070C) and MBUS_BGR_REG (0x0804) */
#define CLK_BUS_DMA			ALLWINNER_CCU_ID(ALLWINNER_CCU_MAIN, 0x070c, 0)
#define CLK_BUS_DMA_M			ALLWINNER_CCU_ID(ALLWINNER_CCU_MAIN, 0x0804, 0)

/* SPIF bus clock, gate in SPIF_BGR_REG (0x0984) */
#define CLK_BUS_SPIF			ALLWINNER_CCU_ID(ALLWINNER_CCU_MAIN, 0x0984, 0)

/* PWM bus/module clock, gate in PWM_BGR_REG (0x07AC) */
#define CLK_BUS_PWM			ALLWINNER_CCU_ID(ALLWINNER_CCU_MAIN, 0x07ac, 0)

/* GPADC bus clock, gate in GPADC_BGR_REG (0x09EC) */
#define CLK_BUS_GPADC			ALLWINNER_CCU_ID(ALLWINNER_CCU_MAIN, 0x09ec, 0)

/* UART resets, reset lines in UART_BGR_REG (0x090C) */
#define RST_BUS_UART0			ALLWINNER_CCU_ID(ALLWINNER_CCU_MAIN, 0x090c, 16)
#define RST_BUS_UART1			ALLWINNER_CCU_ID(ALLWINNER_CCU_MAIN, 0x090c, 17)
#define RST_BUS_UART2			ALLWINNER_CCU_ID(ALLWINNER_CCU_MAIN, 0x090c, 18)
#define RST_BUS_UART3			ALLWINNER_CCU_ID(ALLWINNER_CCU_MAIN, 0x090c, 19)
#define RST_BUS_UART4			ALLWINNER_CCU_ID(ALLWINNER_CCU_MAIN, 0x090c, 20)
#define RST_BUS_UART5			ALLWINNER_CCU_ID(ALLWINNER_CCU_MAIN, 0x090c, 21)

/* TWI resets, reset lines in TWI_BGR_REG (0x091C) */
#define RST_BUS_TWI0			ALLWINNER_CCU_ID(ALLWINNER_CCU_MAIN, 0x091c, 16)
#define RST_BUS_TWI1			ALLWINNER_CCU_ID(ALLWINNER_CCU_MAIN, 0x091c, 17)
#define RST_BUS_TWI2			ALLWINNER_CCU_ID(ALLWINNER_CCU_MAIN, 0x091c, 18)

/* SPI resets, reset lines in SPI_BGR_REG (0x096C) */
#define RST_BUS_SPI0			ALLWINNER_CCU_ID(ALLWINNER_CCU_MAIN, 0x096c, 16)
#define RST_BUS_SPI1			ALLWINNER_CCU_ID(ALLWINNER_CCU_MAIN, 0x096c, 17)

/* SPIF reset, reset line in SPIF_BGR_REG (0x0984) */
#define RST_BUS_SPIF			ALLWINNER_CCU_ID(ALLWINNER_CCU_MAIN, 0x0984, 16)

/* PWM reset, reset line in PWM_BGR_REG (0x07AC) */
#define RST_BUS_PWM			ALLWINNER_CCU_ID(ALLWINNER_CCU_MAIN, 0x07ac, 16)

/* GPADC reset, reset line in GPADC_BGR_REG (0x09EC) */
#define RST_BUS_GPADC			ALLWINNER_CCU_ID(ALLWINNER_CCU_MAIN, 0x09ec, 16)

/* DMA reset, reset line in DMA_BGR_REG (0x070C) */
#define RST_BUS_DMA			ALLWINNER_CCU_ID(ALLWINNER_CCU_MAIN, 0x070c, 16)

/*
 * Display clocks, resets and PLL outputs.
 *
 * Module clocks use the gate bit of their clock register (bit 31), bus
 * clocks the gate bit of the bus gating/reset register (bit 0) and the
 * matching reset the bit 16 of the same register. PLL outputs derived by
 * a divider or a gate (PLL_PERI_2X/1X) use a virtual bit number so that
 * every clock has a distinct id.
 */
#define CLK_PLL_PERI_2X			ALLWINNER_CCU_ID(ALLWINNER_CCU_MAIN, 0x0020, 16)
#define CLK_PLL_PERI_1X			ALLWINNER_CCU_ID(ALLWINNER_CCU_MAIN, 0x0020, 17)
#define CLK_PLL_VIDEO0_4X		ALLWINNER_CCU_ID(ALLWINNER_CCU_MAIN, 0x0040, 31)

#define CLK_DE				ALLWINNER_CCU_ID(ALLWINNER_CCU_MAIN, 0x0600, 31)
#define CLK_BUS_DE			ALLWINNER_CCU_ID(ALLWINNER_CCU_MAIN, 0x060c, 0)
#define RST_BUS_DE			ALLWINNER_CCU_ID(ALLWINNER_CCU_MAIN, 0x060c, 16)

#define CLK_G2D				ALLWINNER_CCU_ID(ALLWINNER_CCU_MAIN, 0x0630, 31)
#define CLK_BUS_G2D			ALLWINNER_CCU_ID(ALLWINNER_CCU_MAIN, 0x063c, 0)
#define RST_BUS_G2D			ALLWINNER_CCU_ID(ALLWINNER_CCU_MAIN, 0x063c, 16)
#define CLK_BUS_G2D_M			ALLWINNER_CCU_ID(ALLWINNER_CCU_MAIN, 0x0804, 10)

#define CLK_COMBOPHY0			ALLWINNER_CCU_ID(ALLWINNER_CCU_MAIN, 0x0aa0, 31)
#define CLK_BUS_COMBOPHY0		ALLWINNER_CCU_ID(ALLWINNER_CCU_MAIN, 0x0aa4, 0)

#define CLK_BUS_DPSS_TOP		ALLWINNER_CCU_ID(ALLWINNER_CCU_MAIN, 0x0abc, 0)
#define RST_BUS_DPSS_TOP		ALLWINNER_CCU_ID(ALLWINNER_CCU_MAIN, 0x0abc, 16)

#define CLK_DSI				ALLWINNER_CCU_ID(ALLWINNER_CCU_MAIN, 0x0b24, 31)
#define CLK_BUS_DSI			ALLWINNER_CCU_ID(ALLWINNER_CCU_MAIN, 0x0b4c, 0)
#define RST_BUS_DSI			ALLWINNER_CCU_ID(ALLWINNER_CCU_MAIN, 0x0b4c, 16)

#define CLK_TCONLCD			ALLWINNER_CCU_ID(ALLWINNER_CCU_MAIN, 0x0b60, 31)
#define CLK_BUS_TCONLCD			ALLWINNER_CCU_ID(ALLWINNER_CCU_MAIN, 0x0b7c, 0)
#define RST_BUS_TCONLCD			ALLWINNER_CCU_ID(ALLWINNER_CCU_MAIN, 0x0b7c, 16)

#define RST_BUS_LVDS0			ALLWINNER_CCU_ID(ALLWINNER_CCU_MAIN, 0x0bac, 16)

#define CLK_PWM_BL			ALLWINNER_CCU_ID(ALLWINNER_CCU_MAIN, 0x0790, 31)
#define CLK_BUS_PWM_BL			ALLWINNER_CCU_ID(ALLWINNER_CCU_MAIN, 0x0794, 0)
#define RST_BUS_PWM_BL			ALLWINNER_CCU_ID(ALLWINNER_CCU_MAIN, 0x0794, 16)

/* USB: PHY gate/reset in USB_BGR_REG (0x0a70), controllers in USBOTG0_BGR_REG (0x0a8c) */
#define CLK_BUS_USB			ALLWINNER_CCU_ID(ALLWINNER_CCU_MAIN, 0x0a70, 31)
#define RST_USB_PHY0			ALLWINNER_CCU_ID(ALLWINNER_CCU_MAIN, 0x0a70, 30)
#define CLK_BUS_USB_OTG			ALLWINNER_CCU_ID(ALLWINNER_CCU_MAIN, 0x0a8c, 8)
#define CLK_BUS_USB_EHCI		ALLWINNER_CCU_ID(ALLWINNER_CCU_MAIN, 0x0a8c, 4)
#define CLK_BUS_USB_OHCI		ALLWINNER_CCU_ID(ALLWINNER_CCU_MAIN, 0x0a8c, 0)
#define RST_BUS_USB_OTG			ALLWINNER_CCU_ID(ALLWINNER_CCU_MAIN, 0x0a8c, 24)
#define RST_BUS_USB_EHCI		ALLWINNER_CCU_ID(ALLWINNER_CCU_MAIN, 0x0a8c, 20)
#define RST_BUS_USB_OHCI		ALLWINNER_CCU_ID(ALLWINNER_CCU_MAIN, 0x0a8c, 16)

/* Clock / reset register offsets in the main CCU, used by the dtsi */
#define SUN252I_F101_CCU_UART_BGR_REG	0x090c
#define SUN252I_F101_CCU_APB_UART_REG	0x0528
#define SUN252I_F101_CCU_PLL_PERI_REG	0x0020

#endif /* ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_SUN252I_F101_CCU_H_ */
